### ISSUE TITLE
Error en instalación

### ISSUE THREAD

**Issue by urielcrampton** [kikeelectronico/Homeware-LAN#63]
Hola! Discúlpenme pero soy novato. Cuando instalo el siguiente paso en la raspberry: sudo sh bash/install.sh me aparece el siguiente error al final. ¿Qué podrá ser? Gracias!
Already up-to-date.
Failed to restart homewareMQTT.service: Unit homewareMQTT.service not found
Failed to restart homewareTasks.service: Unit homewareTasks.service not found
Failed to restart homewareRedis.service: Unit homewareRedis.service not found
Failed to restart homeware.service: Unit homeware.service not found
\The upgrader has finished.

**Comment by icemanmex** [comment]
Prueba ejecutando esto:

cd /home/pi/Homeware-LAN
sudo cp configuration_templates/homeware.service /lib/systemd/system/
chmod 744 homeware.sh
sudo systemctl start homeware

Para revisar si levanto ejecuta esto:
 sudo systemctl status homeware

en alguna de las lineas debería aparecer algo como esto:

 Active: active (**running**) since Thu 2020-07-16 23:25:08 UTC; 2s ago

**Comment by urielcrampton** [comment]
Hi! Thank you very much for your answer.
I get the following error:
pi @ raspberrypi: ~ / Homeware-LAN $ sudo systemctl start homeware
Failed to start homeware.service: Unit homeware.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status homeware.service' for details.


Thank you!

**Comment by icemanmex** [comment]
Que tal Uriel, saludos desde México. A mi me salia un problema parecido y lo solucione con lo siguiente:

- **cd /home/pi/Homeware-LAN**

- **cp data.py data.py.ori**

- **En el archivo data.py busca la siguiente linea:**

     self.redis = redis.Redis("localhost")
la cual debe quedar así:
    self.redis = redis.StrictRedis(host="localhost", port=6379, charset="utf-8", decode_responses=True)


- **Del archivo homeware.sh poner las siguientes lineas despues de la primera:**
    SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
    cd $SCRIPTPATH

  Debería quedar algo como esto:

     #!/bin/bash

      SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
      cd $SCRIPTPATH
      gunicorn -w 1 -b 0.0.0.0:5001 homeware:app


- **Por ultimo del archivo /lib/systemd/system/homeware.service**
  
  quita o comenta esta linea:
      WorkingDirectory=/home/pi/Homeware-LAN/

  y de la siguiente linea siguiente quita el "sh"
     ExecStart=sh /home/pi/Homeware-LAN/homeware.sh
  debe quedar así:
    ExecStart=/home/pi/Homeware-LAN/homeware.sh





Yo con esto lo pude solucionar, espero te sirva de ayuda.

**Comment by urielcrampton** [comment]
Genial, me puedes decir como modifico  el archivo homeware.service ya que no tengo permisos? Muchas gracias!

**Comment by jmdjae** [comment]
Hola icemanmex saludos desde mexico
quisiera saber como se modifica el archivo homeware.service ya que no permite realizar la modificacion

**Comment by icemanmex** [comment]
Que tal @urielcrampton y @jmdjae, antes de modificar el archivo intenten esto (ya que podría se que para ustedes no sea necesario modificar pues yo _NO_ hice la instalación en una Raspberry):

**Primero:** 
sudo redis-server &

sudo systemctl start homeware

sudo systemctl status homeware

Al ejecutar este ultimo comando en alguna de las lineas debería aparecer algo como esto:

Active: active (running) since Thu 2020-07-16 23:25:08 UTC; 2s ago


**Si lo anterior no funciono el comando para editar el archivo es:**

sudo vi /lib/systemd/system/homeware.service
